################################################################################
# Client configuration parameters for submission of twister2 jobs
################################################################################

# cluster name mesos scheduler runs in
twister2.resource.scheduler.mesos.cluster: "example"

# role in cluster
twister2.resource.scheduler.mesos.role: "www-data"

# environment name
twister2.resource.scheduler.mesos.env: "devel"

# mesos job name
twister2.job.name: "basic-mesos"

# A Twister2 job can have multiple sets of compute resources
# Four fields are mandatory: cpu, ram, disk and instances
# workersPerPod shows the number of workers on each pod in Kubernetes. May be omitted in other clusters.
# instances must be divisible by workersPerPod, when workersPerPod is given
worker.compute.resources:
- cpu: 0.4  # number of cores for each worker, may be fractional such as 0.5 or 2.4
  ram: 1024 # ram for each worker as Mega bytes
  disk: 1.0 # volatile disk for each worker as Giga bytes
  instances: 6 # number of worker instances with this specification
#  workersPerPod: 2 # number of workers on each pod in Kubernetes. May be omitted in other clusters.

- cpu: 0.5  # number of cores for each worker, may be fractional such as 0.5 or 2.4
  ram: 1024 # ram for each worker as mega bytes
  disk: 1.0 # volatile disk for each worker as giga bytes. May be zero.
  instances: 4 # number of worker instances with this specification
#  workersPerPod: 2 # number of workers on each pod in Kubernetes. May be omitted in other clusters.


# nfs server address
nfs.server.address: "149.165.150.81"

# nfs server path
nfs.server.path: "/nfs/shared-mesos/twister2"

# worker port
twister2.worker_port: "31000"

# desired nodes
#twister2.desired_nodes: "149.165.150.xx,149.165.150.xx,149.165.150.xx"
twister2.desired_nodes: "all"

twister2.use_docker_container: "true"