# the directory where the file will be uploaded, make sure the user has the necessary permissions
# to upload the file here.
twister2.uploader.directory: "/var/www/html/twister2/mesos/"

#twister2.uploader.directory.repository: "/var/www/html/twister2/mesos/"

# This is the scp command options that will be used by the uploader, this can be used to
# specify custom options such as the location of ssh keys.
twister2.uploader.scp.command.options: "--chmod=+rwx"

# The scp connection string sets the remote user name and host used by the uploader.
twister2.uploader.scp.command.connection: "root@149.165.150.81"

# The ssh command options that will be used when connecting to the uploading host to execute
# command such as delete files, make directories.
twister2.uploader.ssh.command.options: ""

# The ssh connection string sets the remote user name and host used by the uploader.
twister2.uploader.ssh.command.connection: "root@149.165.150.81"

# the uploader class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.scp.ScpUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.NullUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"

# this is the method that workers use to download the core and job packages
# it could be  HTTP, HDFS, ..
twister2.uploader.download.method: "HTTP"

# HTTP fetch uri
twister2.HTTP.fetch.uri: "http://149.165.150.81:8082"