dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

jdk: oraclejdk11

cache:
  directories:
    - $HOME/.cache/bazel

before_install:
  - echo "s:======================================"
  - echo "Downloading bazel"
  - wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel_1.1.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_1.1.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.1.0-linux-x86_64.deb
  - echo "Installing C++ and Python"
  - sudo apt-get install g++
  - sudo apt-get install  python-dev python-pip python3-dev python3-pip
  - sudo apt-get install maven

script:
  - echo "PATH CHECK:vb"
  - bazel version
  - echo " BAZEL BUILD START"
  - bazel build --config=ubuntu twister2/... --action_env=JAVA_HOME
  - echo " BAZEL BUILD END"
  - bazel test --config=ubuntu twister2/... --action_env=JAVA_HOME
  - echo "BAZEL PACKAGE START"
  - bazel build --config=ubuntu //scripts/package:tarpkgs --action_env=JAVA_HOME
  - echo "BAZEL PACKAGE END"
  - echo "MAVEN BUILD"
  - sh util/mvn/install-local-snapshot.sh
  - echo " END ALL "
  - echo "e:============================================"

notifications:
  slack:
    rooms:
      - dsc-twister:8iGGrATeSkL31CU3X9WQBNQV#build
