dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel_0.8.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.8.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.8.1-linux-x86_64.deb
  - sudo apt-get install g++

install:
  - wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz
  - tar -xzvf openmpi-3.0.0.tar.gz
  - export BUILD=$PWD
  - export OMPI_300=$PWD/openmpi-3.0.0
  - export PATH=$BUILD/bin:$PATH
  - export LD_LIBRARY_PATH=$BUILD/lib:$LD_LIBRARY_PATH
  - cd $OMPI_300
  - ./configure --prefix=$BUILD --enable-mpi-java
  - make;make install
  
script:
  - mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -Dfile=$OMPI_300/ompi/mpi/java/java/mpi.jar -DgroupId=ompi -DartifactId=ompijavabinding -Dversion=3.0.0
  - sudo apt-get install git build-essential automake cmake libtool-bin zip libunwind-setjmp0-dev zlib1g-dev unzip pkg-config python-setuptools -y
  - sudo apt-get install  python-dev python-pip
  - bazel build --config=ubuntu twister2/...
  - bazel build --config=ubuntu //scripts/package:tarpkgs

