dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

jdk: oraclejdk11

cache:
  directories:
    - $HOME/.cache/bazel
    - $HOME/.cache/apt

before_install:
  - echo "s:======================================"
  - mkdir -p $HOME/.cache/apt
  - echo "Downloading bazel"
  - wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel_1.1.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_1.1.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.1.0-linux-x86_64.deb
  - |
    exist() {
        [ -e "$1" ]
    }
  - |
    if exist $HOME/.cache/apt/*.deb
    then
        sudo mv $HOME/.cache/apt/*.deb /var/cache/apt/archives/
    fi
  - echo "Installing C++ and Python"
  - sudo apt-get install g++
  - sudo apt-get install python-dev python-pip python3-dev python3-pip
  - sudo apt-get install maven
  - cp /var/cache/apt/archives/*deb $HOME/.cache/apt/

jobs:
  include:
    - stage: "Build Stages"
      script:
        - bazel build --config=ubuntu twister2/... --action_env=JAVA_HOME
        - bazel test --config=ubuntu twister2/... --action_env=JAVA_HOME
      name: "Build & Test"
    - script:
        - bazel build --config=ubuntu //scripts/package:tarpkgs --action_env=JAVA_HOME
      name: "Tar Package"
    - script:
        - sh util/mvn/install-local-snapshot.sh
      name: "Maven Package"

notifications:
  slack:
    rooms:
      - dsc-twister:8iGGrATeSkL31CU3X9WQBNQV#build
