# the package uri
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core.tar.gz"
# the resource manager class
twister2.class.state.manager: "edu.iu.dsc.tws.rsched.statemanagers.fs.SharedFileSystemStateManager"
# launcher class for aurora submission
twister2.class.launcher: edu.iu.dsc.tws.rsched.schedulers.aurora.AuroraLauncher
# the uplaoder class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"

