# This is the Headless Service object that is sent to Kubernetes master 
# when creating a job without external services

apiVersion: v1
kind: Service
metadata:
  name: twister2-service-<jobname>-<job-master>
spec:
  selector:
    app: twister2-service-label-<jobname>-<job-master>
  ports:
  - name: job-master-port
    port: <twister2.job.master.port>
    targetPort: <twister2.job.master.port>
    protocol: TCP

