# This is the Headless Service object that is sent to Kubernetes master 
# when creating a job without external services

apiVersion: v1
kind: Service
metadata:
  name: t2-srv-<jobname>-<jm>
spec:
  selector:
    app: t2-srv-lb-<jobname>-<job-master>
  ports:
  - name: job-master-port
    port: <twister2.job.master.port>
    targetPort: <twister2.job.master.port>
    protocol: TCP

