# This is the Headless Service object that is sent to Kubernetes master 
# when creating a job without external services

apiVersion: v1
kind: Service
metadata:
  name: t2-srv-<jobname>
spec:
  clusterIP: None
  selector:
    app: t2-srv-lb-<jobname>

