# working directory
twister2.resource.scheduler.slurm.working.directory: "${HOME}/.twister2data/jobs/"
# the job id file
twister2.resource.scheduler.slurm.job.id: ""
# slurm script to run
twister2.resource.scheduler.slurm.shell.script: "slurm.sh"
# slurm partition
twister2.resource.scheduler.slurm.partition: ""
# the mpirun command location
twister2.resource.scheduler.mpi.home: ""
# the package uri
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core.tar.gz"
# the resource manager class
twister2.class.state.manager: "edu.iu.dsc.tws.rsched.statemanagers.fs.SharedFileSystemStateManager"
# the launcher class
twister2.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.slurmmpi.SlurmMPILauncher"
# the uplaoder class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"