# working directory
twister2.resource.scheduler.mpi.working.directory: "${HOME}/.twister2data/jobs/"
# mode of the mpi scheduler
twsiter2.resource.scheduler.mpi.mode: "slurm"
# the job id file
twister2.resource.scheduler.mpi.job.id: ""
# slurm script to run
twister2.resource.scheduler.mpi.shell.script: "mpi.sh"
# the mpirun command location
twister2.resource.scheduler.mpi.home: ""
# the name of the core package
twister2.package.core: "twister2-core.tar.gz"
# the package uri
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core.tar.gz"
# the resource manager class
twister2.class.state.manager: "edu.iu.dsc.tws.rsched.statemanagers.fs.SharedFileSystemStateManager"
# the launcher class
twister2.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.slurmmpi.MPILauncher"
# the uplaoder class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"