# a sample statefulset yaml file to create Twister Job Master
# before creating this statefulset, 
#   a service needs to be created for this twister2 job
#   then the persistent volume and 
#   then the persistent volume claim
# need to be created.

apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: <job-name>-<job-master>
  namespace: <kubernetes.namespace>
  labels:
    app: twister2-service-label-<job-name>-<job-master>

spec:
  replicas: 1
  serviceName: twister2-service-<jobname>-<job-master>

  selector:
    matchLabels:
      app: twister2-service-label-<job-name>-<job-master>

  template:
    metadata:
      labels:
        app: twister2-service-label-<job-name>-<job-master>

    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: twister2-storage-<job-name>

      containers:
        name: twister2-job-master
        image: auyar/twister2:v0.01
        imagePullPolicy: <kubernetes.image.pull.policy>
        ports:
          name: job-master-port
          containerPort: <twister2.job.master.port>
          protocol: TCP
        resources:
          requests:
            cpu: <twister2.job.master.cpu>
            memory: <twister2.job.master.ram> + "Mi"
        volumeMounts:
        - name: persistent-volume
          mountPath: /persistent
        env:
          # below values are sample values. 
          # they are calculated for each job
        - name: twister2.job.master.ip
          value: <ip.of.job.master>
        - name: twister2.job.master.port
          value: <port>
        - name: twister2.job.name
          value: <job.name>
        - name: kubernetes.namespace
          value: <k8s.namespace>
        - name: twister2.worker.instances
          value: <value>
        - name: twister2.job.master.assigns.worker.ids
          value: <true or false>
        - name: job.master.persistent.job.directory
          value: <value>
        - name: twister2.worker.ping.interval
          value: <value>
        - name: persistent.logging.requested
          value: <true or false>
        - name: twister2.logging.level
          value: <value>
        - name: twister2.logging.redirect.sysouterr
          value: <value>
        - name: twister2.logging.max.file.size.mb
          value: <value>
        - name: twister2.logging.maximum.files
          value: <value>
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
                fieldPath: status.podIP


