twister2.uploader.directory: "${HOME}/.twister2/repository"

# the uplaoder class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"

# this is the method that workers use to download the core and job packages
# it could be  HTTP, HDFS, ..
twister2.uploader.download.method: "HTTP"

