twister2.network.channel.class: "edu.iu.dsc.tws.comms.mpi.TWSMPIChannel"

# the buffer size to be used
twister2.network.buffer.size: 1024000

# number of send buffers to be used
twister2.network.sendBuffer.count: 4

# number of receive buffers to be used
twister2.network.receiveBuffer.count: 4

# channel pending messages
twister2.network.channel.pending.size: 2048

# the send pending messages
twister2.network.send.pending.max: 4

# group up to 8 ~ 16 messages
twister2.network.partition.message.group.low_water_mark: 8000

# this is the max number of messages to group
twister2.network.partition.message.group.high_water_mark: 16000

# in batch partition operations, this value will be used to create mini batches
# within partial receivers
twister2.network.partition.batch.grouping.size: 10000

# For disk based operations, this directory list will be used to persist incoming messages.
# This can be used to balance the load between multiple devices, by specifying directory locations
# from different devices.
twister2.network.ops.persistent.dirs: ["${TWISTER2_HOME}/persistent/"]

# the maximum amount of bytes kept in memory for operations that goes to disk
twister2.network.shuffle.memory.bytes.max: 102400000

# the maximum number of records kept in memory for operations that goes to dist
twister2.network.shuffle.memory.records.max: 102400000

# size of the shuffle file (10MB default)
twister2.network.shuffle.file.bytes.max: 10000000

# no of parallel IO operations permitted
twister2.network.shuffle.parallel.io: 2

# the keyed reduce algorithm
twister2.stream.keyed.reduce.op: "partition"

# the algorithm for gathering data
twister2.stream.keyed.gather.op: "partition"

# the partitioning algorithm
twister2.network.partition.algorithm: "simple"

# the keyed reduce algorithm
twister2.batch.keyed.reduce.op: "partition"

# the algorithm for gathering data
twister2.batch.keyed.gather.op: "partition"

# the partitioning algorithm
twister2.batch.partition.algorithm: "simple"
