# working directory
twister2.resource.scheduler.mpi.working.directory: "${HOME}/.twister2/jobs"
# the launcher class
twister2.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.standalone.StandaloneLauncher"
# The URI of Nomad API
twister2.nomad.scheduler.uri:             http://127.0.0.1:4646
# The nomad schedules cpu resources in terms of clock frequency (e.g. MHz), while Heron topologies
# specify cpu requests in term of cores.  This config maps core to clock freqency.
twister2.nomad.core.freq.mapping: 2000

twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"