###################################################################
# Logging related settings
# for Twister2 workers
###################################################################

# logging level: FINEST, FINER, FINE, CONFIG, INFO, WARNING, SEVERE
# default value is INFO
twister2.logging.level: "INFO"

# Do workers request persistent logging? it could be true or false
# default value is false
persistent.logging.requested: true

# whether System.out and System.err should be redircted to log files
# When System.out and System.err are redirected to log file,
# All messages are only saved in log files. Only a few intial messages are shown on Dashboard.
# Otherwise, Dashboard has the complete messages,
# log files has the log messages except System.out and System.err.
twister2.logging.redirect.sysouterr: false

# The maximum log file size in MB
twister2.logging.max.file.size.mb: 100

# The maximum number of log files for each worker
twister2.logging.maximum.files: 5

# the java utils log file format to be used
twister2.logging.format: "[%1$tF %1$tT] [%4$s] %3$s: %5$s %6$s %n"

###################################################################
# Twister2 Job Master related settings
###################################################################

twister2.job.master.used: true

# if true, the job master runs in the submitting client
# if false, job master runs as a separate process in the cluster
# by default, it is true
# when the job master runs in the submitting client, this client has to be submitting the job from a machine in the cluster
twister2.job.master.runs.in.client: true

# if true, job master assigns the worker IDs,
# if false, workers have their IDs when regitering with the job master
twister2.job.master.assigns.worker.ids: false

twister2.worker.to.job.master.response.wait.duration: 100000

###################################################################################
# WorkerController related config parameters
###################################################################################

# amount of timeout for all workers to join the job
# in milli seconds
twister2.worker.controller.max.wait.time.for.all.workers.to.join: 100000

# amount of timeout on barriers for all workers to arrive
# in milli seconds
twister2.worker.controller.max.wait.time.on.barrier: 100000

###################################################################
# Dashboard related settings
###################################################################

# Dashboard server host address and port
# if this parameter is not specified, then job master will not try to connect to Dashboard
# twister2.dashboard.host: "http://localhost:8080"
