#Home directory of the hadoop
twister2.data.hadoop.home: "${HADOOP_HOME}"

#Specify the URL of the namenode with port
twister2.data.hdfs.url: "hdfs://hostname.domain.name:9000"

#specify the hdfs class
twister2.data.hdfs.class: "org.apache.hadoop.hdfs.DistributedFileSystem"

#Specify the hdfs key
twister2.data.hdfs.implementation.key: "fs.hdfs.impl"

#Specify the config directory of the hdfs
twister2.data.hdfs.config.directory: "${HADOOP_HOME}/etc/hadoop/core-site.xml"

#Specify the data directory of the hdfs
twister2.data.hdfs.data.directory: "${HADOOP_HOME}/etc/hadoop/hdfs-site.xml"

#Specify the name of the namenode
twister2.data.hdfs.namenode: "hostname.domain.name"

#Specify the namenode port
twister2.data.hdfs.namenode.port: "9000"
